export const DATA_VERSION = 4;

const starAgeGroup = {
  1: 'U-8',
  2: 'U-9',
  3: 'U-11',
  4: 'U-13',
  5: 'U-15+',
};

const dribblingStarGroups = [
  {
    tier: 1,
    names: [
      'Directional Nutmeg',
      'Ball Juggle',
      'Open Up Fake Shot Left',
      'Open Up Fake Shot Right',
      'Flick Up for Volley',
      'First Time Feint Turn',
    ],
  },
  {
    tier: 2,
    names: [
      'Feint Forward And Turn',
      'Body Feint Right',
      'Body Feint Left',
      'Stepover Right',
      'Stepover Left',
      'Reverse Stepover Right',
      'Reverse Stepover Left',
      'Ball Roll Left',
      'Ball Roll Right',
      'Drag Back',
    ],
  },
  {
    tier: 3,
    names: [
      'Heel Flick',
      'Roulette Right',
      'Roulette Left',
      'Fake Left and Go Right',
      'Fake Right and Go Left',
      'Heel Chop Left',
      'Heel Chop Right',
      'Feint Left and Exit Right',
      'Feint Right and Exit Left',
      'Stutter Feint',
    ],
  },
  {
    tier: 4,
    names: [
      'Ball Hop',
      'Ball Roll Drag',
      'Drag Back Turn',
      'Flair Nutmegs',
      'Heel to Heel Flick',
      'Simple Rainbow',
      'Spin Left',
      'Spin Right',
      'Stop and Turn Left',
      'Stop and Turn Right',
      'Ball Roll Cut Right',
      'Ball Roll Cut Left',
      'Fake Pass',
      'Fake Pass Exit Left',
      'Fake Pass Exit Right',
      'Quick Ball Rolls',
      'Lane Change Left',
      'Lane Change Right',
      'Three Touch Roulette Left',
      'Three Touch Roulette Right',
      'Drag Back Spin Left',
      'Drag Back Spin Right',
      'Drag to Heel',
      'Heel to Ball Roll',
      'Ball Roll Cut',
    ],
  },
  {
    tier: 5,
    names: [
      'Elastico',
      'Reverse Elastico',
      'Advanced Rainbow',
      'Hocus Pocus',
      'Triple Elastico',
      'Ball Roll & Flick Left',
      'Ball Roll & Flick Right',
      'Heel Flick Turn',
      'Sombrero Flick',
      'Turn and Spin Left',
      'Turn and Spin Right',
      'Ball Roll Fake Left',
      'Ball Roll Fake Right',
      'Ball Roll Fake Turn',
      'Rabona Fake',
      'Elastico Chop Left',
      'Elastico Chop Right',
      'Spin Flick',
      'Flick Over',
      'Tornado Spin',
      'Heel Fake',
      'Flair Rainbow',
      'Sombrero Flick Backwards',
      'Sombrero Flick Left',
      'Sombrero Flick Right',
      'Around the World',
      'In Air Elastico',
      'Reverse in Air Elastico',
      'Flick Up',
      'Chest Flick',
      'T. Around the World',
      'Toe Drag Stepover',
      'Trickster Rainbow',
    ],
  },
];

// Assign ids after existing skills while tagging age group by difficulty tier.
let nextSkillId = 8;
const dribblingSkillEntries = dribblingStarGroups.flatMap(({ tier, names }) =>
  names.map((name) => ({
    id: nextSkillId++,
    categoryId: 2,
    name,
    ageGroup: starAgeGroup[tier],
    description: `${tier}-Star skill move`,
  }))
);

// Technical skills from images organized by category
const technicalSkills = [
  // Passing & First Touch (category 3)
  { categoryId: 3, name: 'Inside First Touch', ageGroup: 'U-8' },
  { categoryId: 3, name: 'Outside First Touch', ageGroup: 'U-8' },
  { categoryId: 3, name: 'Sole First Touch', ageGroup: 'U-9' },
  { categoryId: 3, name: 'Lace First Touch', ageGroup: 'U-9' },
  { categoryId: 3, name: 'Chest Aerial First Touch', ageGroup: 'U-10' },
  { categoryId: 3, name: 'Thigh Aerial First Touch', ageGroup: 'U-10' },
  { categoryId: 3, name: 'Lace Aerial First Touch', ageGroup: 'U-11' },
  { categoryId: 3, name: 'Inside Aerial First Touch', ageGroup: 'U-11' },
  { categoryId: 3, name: 'Outside Aerial First Touch', ageGroup: 'U-11' },
  { categoryId: 3, name: 'Head Aerial First Touch', ageGroup: 'U-12' },
  { categoryId: 3, name: 'Sole Aerial First Touch', ageGroup: 'U-12' },
  { categoryId: 3, name: 'Inside Bounce First Touch', ageGroup: 'U-10' },
  { categoryId: 3, name: 'Outside Bounce First Touch', ageGroup: 'U-10' },
  { categoryId: 3, name: 'Sole Bounce First Touch', ageGroup: 'U-11' },
  { categoryId: 3, name: 'Short Pass', ageGroup: 'U-8' },
  { categoryId: 3, name: 'Short Trivela', ageGroup: 'U-12' },
  
  // Shooting & Finishing (category 4)
  { categoryId: 4, name: 'Power Shot', ageGroup: 'U-9' },
  { categoryId: 4, name: 'Finesse Shot', ageGroup: 'U-10' },
  { categoryId: 4, name: 'Toe Poke', ageGroup: 'U-9' },
  { categoryId: 4, name: 'Backheel Shot', ageGroup: 'U-12' },
  { categoryId: 4, name: 'Trivela Shot', ageGroup: 'U-13' },
  { categoryId: 4, name: 'Chip Shot', ageGroup: 'U-11' },
  { categoryId: 4, name: 'Knuckleball Shot', ageGroup: 'U-14' },
  { categoryId: 4, name: 'Forward Lace Half-Volley', ageGroup: 'U-11' },
  { categoryId: 4, name: 'Inside Side Half-Volley', ageGroup: 'U-11' },
  { categoryId: 4, name: 'Forward Inside Volley', ageGroup: 'U-12' },
  { categoryId: 4, name: 'Forward Lace Volley', ageGroup: 'U-12' },
  { categoryId: 4, name: 'Lace Side Volley', ageGroup: 'U-13' },
  { categoryId: 4, name: 'Forward Bicycle kick', ageGroup: 'U-14' },
  { categoryId: 4, name: 'Scissor Kick', ageGroup: 'U-13' },
  { categoryId: 4, name: 'Overhead Bicycle Kick', ageGroup: 'U-15+' },
  { categoryId: 4, name: 'Forward Lace Dropkick', ageGroup: 'U-12' },
  { categoryId: 4, name: 'Forward Inside Dropkick', ageGroup: 'U-12' },
  { categoryId: 4, name: 'Lace Side Dropkick', ageGroup: 'U-13' },
  { categoryId: 4, name: 'Inside Side Dropkick', ageGroup: 'U-13' },
  { categoryId: 4, name: 'Trivela Dropkick', ageGroup: 'U-14' },
  { categoryId: 4, name: 'Power Penalty', ageGroup: 'U-10' },
  { categoryId: 4, name: 'Placement Penalty', ageGroup: 'U-10' },
  { categoryId: 4, name: 'Stutter-Step Penalty', ageGroup: 'U-12' },
  { categoryId: 4, name: 'Panenka Penalty', ageGroup: 'U-13' },
  { categoryId: 4, name: 'Power Free Kick', ageGroup: 'U-12' },
  { categoryId: 4, name: 'Curved Free Kick', ageGroup: 'U-13' },
  { categoryId: 4, name: 'Trivela Free Kick', ageGroup: 'U-14' },
  { categoryId: 4, name: 'Knuckleball Free Kick', ageGroup: 'U-15+' },
  
  // Long Passing (category 6)
  { categoryId: 6, name: 'Driven Pass', ageGroup: 'U-11' },
  { categoryId: 6, name: 'Lofted Pass', ageGroup: 'U-11' },
  { categoryId: 6, name: 'Curved Long Pass', ageGroup: 'U-13' },
  { categoryId: 6, name: 'Long Trivela', ageGroup: 'U-14' },
  
  // Throw-Ins (category 7)
  { categoryId: 7, name: 'Standing Throw-In', ageGroup: 'U-8' },
  { categoryId: 7, name: 'Running Throw-In', ageGroup: 'U-9' },
  
  // Defending & Tackling (category 8)
  { categoryId: 8, name: 'Jockeying', ageGroup: 'U-9' },
  { categoryId: 8, name: 'Standing Tackle', ageGroup: 'U-9' },
  { categoryId: 8, name: 'Interception', ageGroup: 'U-10' },
  { categoryId: 8, name: 'Block Tackle', ageGroup: 'U-10' },
  { categoryId: 8, name: 'Headed Clearance', ageGroup: 'U-11' },
  { categoryId: 8, name: 'Slide Tackle', ageGroup: 'U-12' },
  { categoryId: 8, name: 'Shielding', ageGroup: 'U-10' },
  
  // Heading (category 9)
  { categoryId: 9, name: 'Standing Header', ageGroup: 'U-10' },
  { categoryId: 9, name: 'Glancing Header', ageGroup: 'U-11' },
  { categoryId: 9, name: 'Flick-On Header', ageGroup: 'U-11' },
  { categoryId: 9, name: 'Forward Aerial Header', ageGroup: 'U-12' },
  { categoryId: 9, name: 'Glancing Aerial Header', ageGroup: 'U-12' },
  { categoryId: 9, name: 'Aerial Flick-On Header', ageGroup: 'U-13' },
  { categoryId: 9, name: 'Diving Header', ageGroup: 'U-13' },
  
  // Ball Mastery (category 1) - New skills
  { categoryId: 1, name: 'Sprint Dribble', ageGroup: 'U-8' },
  { categoryId: 1, name: 'Outside Dribble', ageGroup: 'U-8' },
  { categoryId: 1, name: 'Sole Dribble', ageGroup: 'U-8' },
  { categoryId: 1, name: 'Inside Zig-Zag', ageGroup: 'U-9' },
  { categoryId: 1, name: 'Outside Zig-Zag', ageGroup: 'U-9' },
  { categoryId: 1, name: 'Combo Zig-Zag', ageGroup: 'U-10' },
  { categoryId: 1, name: 'Skill Move Combo', ageGroup: 'U-11' },
  { categoryId: 1, name: 'Foot Feint', ageGroup: 'U-9' },
  { categoryId: 1, name: 'La Croqueta', ageGroup: 'U-11' },
  { categoryId: 1, name: 'Scoop Turn', ageGroup: 'U-11' },
  { categoryId: 1, name: 'Bridge Skill', ageGroup: 'U-12' },
  { categoryId: 1, name: 'Directional Cut', ageGroup: 'U-9' },
  { categoryId: 1, name: 'Stepover Turn', ageGroup: 'U-10' },
  
  // Juggling (category 10)
  { categoryId: 10, name: 'Lace Juggling', ageGroup: 'U-9' },
  { categoryId: 10, name: 'Inside Foot Juggling', ageGroup: 'U-9' },
  { categoryId: 10, name: 'Outside Foot Juggling', ageGroup: 'U-10' },
  { categoryId: 10, name: 'Thigh Juggling', ageGroup: 'U-10' },
  { categoryId: 10, name: 'Head Juggling', ageGroup: 'U-11' },
  { categoryId: 10, name: 'Combo Juggling', ageGroup: 'U-12' },
];

const technicalSkillEntries = technicalSkills.map((skill) => ({
  id: nextSkillId++,
  categoryId: skill.categoryId,
  name: skill.name,
  ageGroup: skill.ageGroup,
  description: 'Technical skill',
}));

export const initialData = {
  version: DATA_VERSION,
  categories: [
    { id: 1, name: 'Ball Mastery', icon: '⚽', color: '#E63946' },
    { id: 2, name: 'Dribbling & Skill Moves', icon: '🏃', color: '#F4A261' },
    { id: 3, name: 'Passing & First Touch', icon: '🎯', color: '#2A9D8F' },
    { id: 4, name: 'Shooting & Finishing', icon: '🥅', color: '#E76F51' },
    { id: 5, name: 'Crossing', icon: '↗️', color: '#264653' },
    { id: 6, name: 'Long Passing', icon: '📏', color: '#023E8A' },
    { id: 7, name: 'Throw-Ins', icon: '🙌', color: '#6A4C93' },
    { id: 8, name: 'Defending & Tackling', icon: '🛡️', color: '#1D3557' },
    { id: 9, name: 'Heading', icon: '🤕', color: '#457B9D' },
    { id: 10, name: 'Juggling', icon: '🎪', color: '#9B2226' },
  ],
  skills: [
    { id: 1, categoryId: 1, name: 'Toe Taps', ageGroup: 'U-7', description: 'Basic ball control with alternating feet' },
    { id: 2, categoryId: 1, name: 'Sole Rolls', ageGroup: 'U-7', description: 'Rolling the ball with the sole of the foot' },
    { id: 3, categoryId: 1, name: 'Inside-Outside Touch', ageGroup: 'U-8', description: 'Alternating between inside and outside of foot' },
    { id: 4, categoryId: 5, name: 'Driven Cross', ageGroup: 'U-10', description: 'Low, hard cross into the box' },
    { id: 5, categoryId: 5, name: 'Aerial Cross', ageGroup: 'U-11', description: 'High, looping cross for headers' },
    { id: 6, categoryId: 5, name: 'Curved Cross', ageGroup: 'U-12', description: 'Cross with curve away from goalkeeper' },
    { id: 7, categoryId: 5, name: 'Trivela Cross', ageGroup: 'U-14', description: 'Outside of foot curved cross' },
    ...dribblingSkillEntries,
    ...technicalSkillEntries,
  ],
  exercises: [
    { id: 1, skillId: 1, name: 'Basic Toe Tap Drill', videoUrl: '', difficulty: 1, description: 'Stand over the ball and alternate touching the top with each foot' },
    { id: 2, skillId: 1, name: 'Speed Toe Taps', videoUrl: '', difficulty: 2, description: 'Increase speed while maintaining control' },
    { id: 3, skillId: 4, name: 'Driven Cross Mastery', videoUrl: '', difficulty: 4, description: 'Practice low driven crosses from wide positions' },
    { id: 4, skillId: 4, name: 'Cut-back Cross', videoUrl: '', difficulty: 2, description: 'Cross from byline back to edge of box' },
  ],
};
